#ifndef HF_MODEL_HPP
#define HF_MODEL_HPP
/*
PROJECT: NOSTRUM, https://nostrum-project.it
AUTHORS: Alessio Castorrini, Riccardo Broglia, Rosalba Cardamone
DATE: 2026-01-01

DESCRIPTION:
HF_Model class: physical model for a specific application. The class includes member variables and functions that allow us to manipulate and utilize the model effectively. The implementation details of the member functions will be provided in the corresponding source file (HF_Model.cpp).

In this example, the HF model is given by the aerodynamic BEMT model of the wind turbine blade, which is designed in the project NOSTRUM.
The base solver for aerodynamics is AeroDyn15, which is a widely used tool for simulating the aerodynamics of wind turbine blades. The HF model will be trained using data from AeroDyn15 simulations, and it will be used to predict the aerodynamic performance of the blade under various conditions.
This class act as an interface for AeroDyn15, allowing to compute the power coefficient for a rigid rotor with the blade geometry defined by the input parameters, and to read the results from the output files. The surrogate model will then be trained on the data generated by this HF model.

NOTE: this implementation is supposed to be serial (no MPI), therefore, the methods class will be computed from the main only by the master process (rank 0), and then the results will be broadcasted to the other processes. 
*/

#include <cmath>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <numeric>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

// Data structures
struct BladeData {
    std::vector<std::string> headerLines;
    std::vector<std::vector<double>> numericData;
};

// HF class definition
class HF_Model {
public:
    HF_Model() = default;
    // Initialization and read files
    void initialize(const std::filesystem::path& projectRoot);

    // Function to load blade data from a file
    BladeData loadBladeData(const std::filesystem::path& bladeFilePath);
    // Other member functions related to the HF model can be declared here
    std::vector<double> extractColumn(const std::vector<std::vector<double>>& data, std::size_t column);
    std::vector<double> gatherByIndices(const std::vector<double>& values, const std::vector<std::size_t>& indices);
    std::vector<double> interpolateLinearProfile(const std::vector<double>& x, double xStart, double xEnd, double yStart, double yEnd);

    // Define upper and lower bounds for the surrogate model parameters
    void defineBounds();

    // Define HF solver
    std::pair<double, double> computeFT(const std::vector<double>& xt);
    std::pair<double, double> computeCPWithTorsionDOF(
        const std::vector<double>& xt,
        const std::vector<double>& xcTheta,
        const std::vector<double>& xs,
        int torsionStartIndex,
        const std::vector<std::vector<double>>& dataBladeBaseline,
        const std::vector<std::string>& headerLines,
        int twistColumnIndex,
        int numberBladeElements,
        int rotCpChannelIndex,
        const std::filesystem::path& projectRoot,
        const std::filesystem::path& aerodynExecutable,
        const std::filesystem::path& aerodynCaseRoot);

    //Read info
    void loadParametersFromConfigFileHF(const std::string& filename);
    // Write info
    void saveDataOnFile(const std::filesystem::path& outputPath);

    // Variables
    std::filesystem::path projectRoot;
    std::filesystem::path aerodynCaseRoot;
    std::filesystem::path aerodynExecutable;
    std::filesystem::path bladeFileName;
    BladeData bladeData;
    std::vector<double> lb;
    std::vector<double> ub;
    std::vector<double> thetaRef;
    std::vector<double> xcTheta;
    int numberBladeElements;
    std::vector<double> xs;
    std::vector<std::size_t> CP_indices;

    int twistID;
    int chordID;
    int spanID;
    int torsionStartID;
    int rotCpChannel;

    double deltaMaxRoot;
    double deltaMaxTip;
    double deltaMaxTorsion;
    double initTorsion;

};




#endif // HF_MODEL_HPP